Sprint_6
itkacheva/Sprint_6 pull request #1
Opened 2023-12-07 07:21 UTC by itkacheva

Автотесты для учебного сервиса «Яндекс.Самокат»

2023-12-10 11:58 UTC, kadirovgm requested changes

2023-12-10 11:58 UTC, kadirovgm commented on conftest.py
> +def driver():
отлично!

2023-12-10 11:58 UTC, kadirovgm commented on conftest.py
> +def pytest_make_parametrize_id(val):
нужно исправить: кажется можно было бы обойтись и без это метода? тем более не фиксутры не должны лежать в файле conftest.py

2023-12-10 11:58 UTC, kadirovgm commented on data.py
> +questions_answers = [
супер!  молодец, что вынесла тестовые данные в отдельный файл! 
только я бы еще посоветовал сгруппировать эти вопросы/ответы в классы, чтобы в data.py можно было хранить еще и другие данные

2023-12-10 11:58 UTC, kadirovgm commented on data.py
> +order_details_1 = [['Шерлок', 'Холмс', 'Бейкер Стрит 221', 'Беговая', '+79532747027', '05.12.2023', 'сутки',
Можно лучше: а ну вот как раз у тебя вопросы/ответы сливаются с order_datails - что не очень хорошо, лучше разбить по классам и поместить в соответсвтующие

например, Questions(), Answers(), Order() итд

2023-12-10 11:58 UTC, kadirovgm commented on locators/order_page_locators.py
> +    VIEW_STATUS_BUTTON = [By.XPATH, ".//div[contains(@class,'Order_NextButton')]/button[text()='Посмотреть статус']"]  # Кнопка Просмотреть статус
Можно лучше: этот и остальные локаторы советую сократить, потому что их можно написать более оптимальными, не теряя в уникальности

2023-12-10 11:58 UTC, kadirovgm commented on pages/home_page.py
> +    def __init__(self, driver):
Нужно исправить: нужно добавить класс BasePage и поместить этот конструктор в нее, а в классам POM страниц достаточно наследоваться от BasePage, чтобы переиспользовать этот конструктор

класс BasePage - это такой родительский класс, в котором содержатся общие методы, такие как: клик по определенному элементу, скролл к определенному элементу, ожидание определенного элемента, изменение табов итд.

То есть эти методы не привязаны к определенной странице, и могут быть переиспользованы в любой POM-странице, стоит сюда добавить именно такие методы.

2023-12-10 11:58 UTC, kadirovgm commented on pages/home_page.py
> +class HomePageScooter:
нужно исправить: стоит наследоваться от BasePage и наследовать все ее базовые методы, чтобы переиспользовать внутри методов HomePageScooter()

2023-12-10 11:58 UTC, kadirovgm commented on pages/home_page.py
> +        element = self.driver.find_element(*HomePageScooterLocators.ORDER_BUTTON_HEADER)
например вот, для того, чтобы кликнуть, ты всегда сначала ищешь его - потом кликаешь

для этого можно сделать базовый метод в классе BasePage, который будет на вход принимать локатор элемента, в внутри метода будет проверять его наличие, а потом кликать

соответсвтенно этот базовый метод можно переиспользовать во всех методах классов страниц

также можно поступать ешще с какими то базовыми действиями, которых можно автоматизировать и сократить код, примеры таких действия еще описывал в комменте выше

2023-12-10 11:58 UTC, kadirovgm commented on pages/home_page.py
> +    def wait_load_answer(self):
Нужно исправить: давай этот метод сделаем базовым и переименуем его (например wait_for_load_element(locator)), потому что он подходит под проверку загрузки любого элемента (достаточно только передать локатор в аргументы функции), а не только "ответа на вопрос"

2023-12-10 11:58 UTC, kadirovgm commented on pages/home_page.py
> +    def switch_on_new_window(self, original_window, new_url):
нужно исправить: это скорее метод BasePage()

2023-12-10 11:58 UTC, kadirovgm commented on pages/order_page.py
> +class OrderPage:
нужно исправить: нужно наследвоваться от BasePage()

2023-12-10 11:58 UTC, kadirovgm commented on pages/order_page.py
> +    def __init__(self, driver):
нужно исправить: после наследования заново прописывать конструктор не нужно будет

2023-12-10 11:58 UTC, kadirovgm commented on pages/order_page.py
> +    def full_order_form(self, buyer_name, buyer_surname, address, metro_station, input_phone, delivery_date, rental_term, color, comment):
отлично! молодец, что объединила мини-методы для заполнения данных в большой высокоуровнеый, потому что в тестах мы должны оставлять только высокоуровневые шаги, засунув под капот всякие ожидания, клики итд

2023-12-10 11:58 UTC, kadirovgm commented on tests/test_flow_ordering_scoote.py
> +    @pytest.mark.parametrize('buyer_name, buyer_surname, address, metro_station, input_phone, delivery_date, '
нужно исправить: для чего тут параметризация? если набор параметров тут один?
давай список order_details_1 просто передавать в в аргументах функции

параметризация - это когда на вход теста передают тестовые данные из разных классов эквивалентности, при этом зная, что тест вернет одно и то же значение

2023-12-10 11:58 UTC, kadirovgm commented on tests/test_flow_ordering_scoote.py
> +    @pytest.mark.parametrize('buyer_name, buyer_surname, address, metro_station, input_phone, delivery_date, '
параметризацию тут можно применить в случае, если передавать параметром кнопки button_header, и button_bottom (то есть этот и тест ниже можно объединить в одну, так как объект тестирования - сделать заказ, а сделать можно двумя способами, при этом ожидаемый результат один)

2023-12-10 11:58 UTC, kadirovgm commented on tests/test_flow_ordering_scoote.py
> +        op.full_order_form(buyer_name, buyer_surname, address, metro_station, input_phone, delivery_date, rental_term
Можно лучше: может fill?

2023-12-10 11:58 UTC, kadirovgm commented on tests/test_flow_ordering_scoote.py
> +        op.click_view_status_button_yes()
нужно исправить: пишем тесты атомарными^ то есть если мы на 26-о строке провереили, что "заказ оформлен", то тест не может идти дальше, потому что если тест упадет на 26-ой строке мы не узнаем что бы было дальше

грубо говоря мы ожидаем одна функциональная проверка = один тест (один ассерт)

2023-12-10 11:58 UTC, kadirovgm commented on tests/test_flow_ordering_scoote.py
> +        hp.click_on_logo_scooter()
нужно исправить: это уже друго тест, давай вынесем отдельно

2023-12-10 11:58 UTC, kadirovgm commented on tests/test_flow_ordering_scoote.py
> +        driver.switch_to.window(original_window)
нужно исправить: это для чего? если нет проверки далее

2023-12-10 11:58 UTC, kadirovgm commented on tests/test_home_page.py
> +        assert hp.get_text_answer() == text_answer
хорошие тест!

2023-12-10 11:58 UTC, kadirovgm commented on urls.py
> +home_page_url = "https://qa-scooter.praktikum-services.ru/"
нужно исправить: давай поместим их в класс Urls() чтобы испортить только нужный класс, а не весь файл

2023-12-11 18:35 UTC, itkacheva commented on conftest.py
> +def pytest_make_parametrize_id(val):
Убрала, но этот метод устраняет проблему с кодировкой
![image](https://github.com/itkacheva/Sprint_6/assets/129445454/0b2aa165-244a-4aee-b646-9619a3b472cb)

2023-12-11 19:01 UTC, itkacheva commented on data.py
> +questions_answers = [
done

2023-12-11 19:01 UTC, itkacheva commented on data.py
> +order_details_1 = [['Шерлок', 'Холмс', 'Бейкер Стрит 221', 'Беговая', '+79532747027', '05.12.2023', 'сутки',
done

2023-12-11 19:01 UTC, itkacheva commented on locators/order_page_locators.py
> +    VIEW_STATUS_BUTTON = [By.XPATH, ".//div[contains(@class,'Order_NextButton')]/button[text()='Посмотреть статус']"]  # Кнопка Просмотреть статус
done

2023-12-11 19:04 UTC, itkacheva commented on tests/test_flow_ordering_scoote.py
> +        driver.switch_to.window(original_window)
done

2023-12-11 19:17 UTC, itkacheva commented on urls.py
> +home_page_url = "https://qa-scooter.praktikum-services.ru/"
done

2023-12-11 19:35 UTC, itkacheva commented on tests/test_flow_ordering_scoote.py
> +        op.click_view_status_button_yes()
done

2023-12-11 19:35 UTC, itkacheva commented on tests/test_flow_ordering_scoote.py
> +        hp.click_on_logo_scooter()
done

2023-12-12 22:50 UTC, kadirovgm approved these changes

2023-12-12 22:50 UTC, kadirovgm commented on data.py
> +class HomePageData:
отлично!

2023-12-12 22:50 UTC, kadirovgm commented on locators/order_page_locators.py
> +    SECTION_TEXT = [By.XPATH, ".//*[contains(@class,'Order_Header')]"]  # текст "Для кого самокат"
супер! стало лучше

2023-12-13 04:18 UTC, merged